/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'
import { Route as ApiCartAddRouteImport } from './routes/api/cart/add'
import { Route as ApiCartRemoveRouteImport } from './routes/api/cart/remove'
import { Route as ApiCartUpdateRouteImport } from './routes/api/cart/update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartAddRoute = ApiCartAddRouteImport.update({
  id: '/api/cart/add',
  path: '/api/cart/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRemoveRoute = ApiCartRemoveRouteImport.update({
  id: '/api/cart/remove',
  path: '/api/cart/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartUpdateRoute = ApiCartUpdateRouteImport.update({
  id: '/api/cart/update',
  path: '/api/cart/update',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/api/cart/add': typeof ApiCartAddRoute
  '/api/cart/remove': typeof ApiCartRemoveRoute
  '/api/cart/update': typeof ApiCartUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/api/cart/add': typeof ApiCartAddRoute
  '/api/cart/remove': typeof ApiCartRemoveRoute
  '/api/cart/update': typeof ApiCartUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/api/cart/add': typeof ApiCartAddRoute
  '/api/cart/remove': typeof ApiCartRemoveRoute
  '/api/cart/update': typeof ApiCartUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/quote'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/quote'
    | '/collections/$handle'
    | '/products/$handle'
    | '/api/cart/add'
    | '/api/cart/remove'
    | '/api/cart/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/quote'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/quote'
    | '/collections/$handle'
    | '/products/$handle'
    | '/api/cart/add'
    | '/api/cart/remove'
    | '/api/cart/update'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/quote'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/quote'
    | '/collections/$handle'
    | '/products/$handle'
    | '/api/cart/add'
    | '/api/cart/remove'
    | '/api/cart/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  QuoteRoute: typeof QuoteRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  ApiCartAddRoute: typeof ApiCartAddRoute
  ApiCartRemoveRoute: typeof ApiCartRemoveRoute
  ApiCartUpdateRoute: typeof ApiCartUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/add': {
      id: '/api/cart/add'
      path: '/api/cart/add'
      fullPath: '/api/cart/add'
      preLoaderRoute: typeof ApiCartAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/remove': {
      id: '/api/cart/remove'
      path: '/api/cart/remove'
      fullPath: '/api/cart/remove'
      preLoaderRoute: typeof ApiCartRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/update': {
      id: '/api/cart/update'
      path: '/api/cart/update'
      fullPath: '/api/cart/update'
      preLoaderRoute: typeof ApiCartUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  QuoteRoute: QuoteRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  ApiCartAddRoute: ApiCartAddRoute,
  ApiCartRemoveRoute: ApiCartRemoveRoute,
  ApiCartUpdateRoute: ApiCartUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
